# This is a basic workflow to help you get started with Actions

name: push-to-remote

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  push-to-remote:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: get the diff of files
        run: git log

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          BEFORE_SHA=$(jq -r '.before' $GITHUB_EVENT_PATH)
          AFTER_SHA=$(jq -r '.after' $GITHUB_EVENT_PATH)
          echo BEFORE_SHA
          echo AFTER_SHA
          echo $GITHUB_EVENT_PATH
